// <auto-generated />
namespace ARFood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AR20200711 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AR20200711));
        
        string IMigrationMetadata.Id
        {
            get { return "202007130306288_AR20200711"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
